### PR TITLE
Update to specification 0.1.1

### PR DESCRIPTION
**Pull request by tschaffter**

### CODE REVIEW

**Comment by tschaffter** [comment]
@vpchung [This PR](https://github.com/Sage-Bionetworks/tool-registry/pull/8/files) (Tool Registry project) does exactly what we want to do here.

**Comment by tschaffter** [comment]
I converted this PR into a draft. Feel free to mark it as "Ready for review" and add me as a reviewer when needed.

**Comment by vpchung** [comment]
@tschaffter it doesn't look like I can request you as a reviewer (probably due to you opening the PR). But I have added functionalities to the Challenge controller!

I wasn't able to get the tests working (kept getting a 500 error), so I have temporarily disabled them. I'm hoping we can go over this during our standup.

**Comment by tschaffter** [comment]
> it doesn't look like I can request you as a reviewer (probably due to you opening the PR).

That's right.

**Comment by tschaffter** [comment]
First error with py3.7

```
_________________________________________________ ERROR collecting openapi_server/test/test_challenge_controller.py __________________________________________________
ImportError while importing test module '/mnt/c/Users/thoma/Documents/dev/rocc-portal/server/openapi_server/test/test_challenge_controller.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openapi_server/test/test_challenge_controller.py:8: in <module>
    from openapi_server.dbmodels.challenge import Challenge as DbChallenge
openapi_server/dbmodels/__init__.py:6: in <module>
    from openapi_server.dbmodels.challenge import Challenge
openapi_server/dbmodels/challenge.py:1: in <module>
    from mongoengine import ListField, ReferenceField, StringField, URLField
E   ModuleNotFoundError: No module named 'mongoengine'
```

**Comment by tschaffter** [comment]
I solved the above error by removing the temp folder *server/.tox* and running `tox` again.

@vpchung Is the error below the one you reported?

```
openapi_server/test/test_challenge_controller.py::TestChallengeController::test_get_challenge FAILED                                                           [100%]

============================================================================== FAILURES ==============================================================================
_____________________________________________________________ TestChallengeController.test_get_challenge _____________________________________________________________

self = <openapi_server.test.test_challenge_controller.TestChallengeController testMethod=test_get_challenge>

    def test_get_challenge(self):
        """Test case for get_challenge

        Get a challenge
        """
        util.create_test_challenge("awesome-challenge")
        headers = {
            'Accept': 'application/json',
        }
        response = self.client.open(
            '/api/v1/challenges/{id}'.format(id='awesome-challenge'),
            method='GET',
            headers=headers)
        self.assert200(response,
>                      'Response body is : ' + response.data.decode('utf-8'))

openapi_server/test/test_challenge_controller.py:88:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/py37/lib/python3.7/site-packages/flask_testing/utils.py:336: in assert200
    self.assertStatus(response, 200, message)
.tox/py37/lib/python3.7/site-packages/flask_testing/utils.py:324: in assertStatus
    self.assertEqual(response.status_code, status_code, message)
E   AssertionError: 500 != 200 : Response body is : {
E     "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
E     "status": 500,
E     "title": "Internal Server Error",
E     "type": "about:blank"
E   }
```

**Comment by vpchung** [comment]
Yep! That's the one, but I'm not sure where that extra `id_` argument is coming from...

I similarly get a 500 error when testing `create_challenge`, due to the following reason:

```
TypeError: create_challenge() missing 1 required positional argument: 'challenge'
```

**Comment by tschaffter** [comment]
> TypeError: create_challenge() missing 1 required positional argument: 'challenge'

This is one peculiar behavior of the openapi generator. Normally the arguments of the controller functions represent the query parameters. However the generator systematically add a parameter that seems to be named following the **name of the schema of the input object**. When the endpoint has at least one query parameter, the additional parameter mentioned above is usually placed last and is given automatically the `=None`, see this [example line](https://github.com/nlpsandbox/data-node/blob/1b37a584052f23f26502c98f73493f8d50244147/server/openapi_server/controllers/dataset_controller.py#L12) that was automatically generated by the generator. However it seems that when an endpoint does not have any query parameter, the generator forgets to add `=None`. Not sure what this extra parameter is used for (its value is never set) aside providing information to the developer on the type of schema to expect as input.

The PR #27 will fix this issue once merged into the branch of this PR.

**Comment by tschaffter** [comment]
@vpchung As briefly mentioned in the description of #27, two issues I have identified are 1) how dates are used and 2) there seems to be issues when saving `Challenge.organizations` and `Challenge.organizers`.

Can you have a look at these two issues?

**Comment by vpchung** [comment]
@tschaffter as mentioned in an external discussion, there were three past challenges that did not have a start/end date that conformed to the proper datetime format. I revisited those challenge sites and was able to get one accurate end date. The other two dates are guesstimates based on the graphs I see in [Challenge Statistics](https://www.synapse.org/#!Synapse:syn2504723/wiki/65150).

**Pull request merged**
